---
apiVersion: 'apps/v1'
kind:       'Deployment'
metadata:
  name: {{ include "cas.fullname" . }}
  labels:
    {{- include "cas.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "cas.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name:   'cas-config'
          configMap:
            name: 'cas-config'

        - name:         'cas-ssl'
          secret:
            secretName: 'cas-ssl'

        - name:   'cas-services'
          configMap:
            name: 'cas-services'
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name:         'http'
              containerPort: 8080
              protocol:     'TCP'
          #livenessProbe:
            #initialDelaySeconds: 60
            #httpGet:
              #path: "{{ .Values.config.casProperties.base_uri }}/logout"
              #port: 8080
          #readinessProbe:
            #initialDelaySeconds: 60
            #httpGet:
              #path: "{{ .Values.config.casProperties.base_uri }}/logout"
              #port: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
            - name:      'cas-config'
              mountPath: "/etc/cas/config"

            - name:      'cas-services'
              mountPath: "/etc/cas/services"

            - name:      'cas-ssl'
              mountPath: "/etc/cas/ssl"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
...
