---
apiVersion: 'v1'
kind:       'Service'
metadata:
  name: {{ include "cas.fullname" . }}
  labels:
    {{- include "cas.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port:       8080
      targetPort: 8080
      protocol:   'TCP'
      name:       'tomcat'
  selector:
    {{- include "cas.selectorLabels" . | nindent 4 }}
...
