apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cob-cas.name" . }}-services
  labels:
    app.kubernetes.io/name: {{ include "cob-cas.name" . }}
    helm.sh/chart: {{ include "cob-cas.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data: 
  {{- (.Files.Glob "files/services/*").AsConfig | nindent 2 }}