apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cob-cas.name" . }}-ssl
  labels:
    app.kubernetes.io/name: {{ include "cob-cas.name" . }}
    helm.sh/chart: {{ include "cob-cas.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data: 
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "files/ssl/*" }}
  {{ base $path }}: '{{ $root.Files.Get $path | b64enc }}'
  {{- end }}