apiVersion: v1
kind: Service
metadata:
  name: {{ include "cob-cas.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cob-cas.name" . }}
    helm.sh/chart: {{ include "cob-cas.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: cas-web

    # - port: 80
    #   targetPort: 80
    #   protocol: TCP
    #   name: http

  selector:
    app.kubernetes.io/name: {{ include "cob-cas.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
