---
- hosts:  'cas'
  become: 'yes'
  roles:
    - 'City-of-Bloomington.tomcat'
  tasks:
    - name: "Update apache configuration"
      template:
        src:   'apache.conf'
        dest:  '/etc/apache2/sites-enabled/conf.d/cas.conf'
      notify:  'apache_restart'

    - name: 'Add drop-in unit file'
      copy:
        src: 'tomcat.service'
        dest: "/etc/systemd/system/{{ tomcat_package }}.service.d/cas.conf"
      notify: 'linux_systemd_reload'

    - name: "Create directories"
      file:
        path:    "{{ item }}"
        state:   "directory"
        owner:   "{{ tomcat_user }}"
        recurse: 'yes'
      with_items:
        - '/etc/cas/config'
        - '/etc/cas/saml'
        - '/etc/cas/services'
        - '/etc/cas/ssl'

    - name: "Configure CAS"
      template:
        src: "cas.properties"
        dest: "/etc/cas/config"
      notify: "tomcat_restart"

    - name: "Configure services"
      copy:
        src:   "{{ item }}"
        dest:  '/etc/cas/services/'
        owner: "{{ tomcat_user }}"
      with_fileglob:
        - "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/cas/services/*.json"
        - "{{ inventory_dir }}/group_vars/cas/services/*.json"
      notify: "tomcat_restart"

    - name: "Configure SAML metadata"
      copy:
        src:   "{{ item }}"
        dest:  '/etc/cas/saml/'
        owner: "{{ tomcat_user }}"
      with_fileglob:
        - "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/cas/saml/*.xml"
        - "{{ inventory_dir }}/group_vars/cas/saml/*.xml"
      notify: "tomcat_restart"

    - name: "Install Webapp"
      copy:
        src:  '../build/libs/cas.war'
        dest: "{{ cas_install_path }}.war"
      notify: "tomcat_restart"
...
