---
- hosts: cas
  become: yes
  roles:
    - City-of-Bloomington.tomcat
  tasks:
    - name: "Update apache configuration"
      template:
        src: cas.conf
        dest: /etc/apache2/sites-enabled/conf.d/cas.conf
        owner: root
        group: root
        mode: 0644
      notify: apache_restart

    - name: "Create configuration directory"
      file:
        path: "/etc/cas/config"
        state: "directory"

    - name: "Create services directory"
      file:
        path: "/etc/cas/services"
        state: "directory"
        owner: "tomcat8"

    - name: "Configure CAS"
      template:
        src: "cas.properties"
        dest: "/etc/cas/config"
      notify: "tomcat_restart"

    - name: "Configure Admin Users"
      template:
        src: "adminusers.properties"
        dest: "/etc/cas/config"
      notify: "tomcat_restart"

    - name: "Configure services"
      template:
        src: "service.json"
        dest: "/etc/cas/services/{{ item.name | regex_replace('[\\s]', '') }}-{{ item.id }}.json"
        owner: "tomcat8"
      with_items: "{{ cas_services }}"
      notify: "tomcat_restart"

    - name: "Install Webapp"
      copy:
        src: "../target/cas.war"
        dest: "{{ cas_install_path }}.war"
      notify: "tomcat_restart"
...
