---
# Default values for cas.
replicaCount: 1

image:
  repository: ''
  tag:        '' # Specify on the command line --set image.tag=X.x.x-abcdef00
  pullPolicy: 'Always'
nameOverride:     ''
fullnameOverride: ''

config:
  casProperties:
    base_uri:     '/cas'
    serverName:   ''
    serverPrefix: ''
    hostName:     ''

    ldap:
      type: 'AUTHENTICATED'
      url: ''
      ConnectStrategy: 'ACTIVE_PASSIVE'
      SSL: true
      StartTLS: false
      baseDN: ''
      searchFilter: 'sAMAccountName={user}'
      bindDN: ''
      bindCredential: ''
      dnFormat: ''
      PrincipalAttributeId:   'sAMAccountName'
      PrincipalAttributeList: 'sAMAccountName,mail,givenName,sn,uid'
    oidc:
      issuer: ''
      claims: 'email'

    crypto:
      webflowSigningKey:    ''
      webflowEncryptionKey: ''
      tgcSigningKey:        ''
      tgcEncryptionKey:     ''

    ssl:
      keyStoreLocation: '/etc/cas/ssl/keystore.p12'
      keyStorePassword: ''


service:
  type: 'ClusterIP'

ingress:
  enabled: true
  hosts:
    - host: ''
      paths: ['/cas']
...
