---
# Default values for cas.
replicaCount: 1

image:
  repository: ''
  tag:        '' # Specify on the command line --set image.tag=X.x.x-abcdef00
  pullPolicy: 'Always'
nameOverride:     ''
fullnameOverride: ''

service:
  type: 'ClusterIP'

ingress:
  enabled: true
  hosts:
    - host: ''
      paths: ['/cas']
...
